---

- hosts: localhost
  tasks:
    - name: update apt cache before running any of the ansible roles
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: localhost
  roles:
    # generic developer VM stuff
    - { role: desktop, tags: "desktop" }
    - { role: readme, tags: "readme" }
    - { role: ansible-lint, tags: "ansible-lint" }
    - { role: testinfra, tags: "testinfra" }
    # yocto workshop toolchain
    - { role: toolchain, tags: "toolchain" }
    - { role: vscode, tags: "vscode" }
    - { role: picocom, tags: "picocom" }
